#!/bin/bash
# Bundles the whole module into one self-contained installer. Every runtime
# file is embedded as base64, so it needs no `git clone` and works with this
# repo private.
#
#   scripts/build-installer.sh                         # for storage.gosecureserver.in
#   scripts/build-installer.sh https://other.example   # for somewhere else
#
# Produces two files — upload BOTH to the web root of that URL:
#
#   dist/install.sh   the installer:   curl -sSL <url>/install.sh | bash
#   dist/VERSION      what WHM's "Check for Updates" compares against
#
# To release: bump VERSION, rebuild, re-upload both. Every server then sees
# the update in WHM. Re-run after changing anything under bin/, lib/, etc/,
# plugin/, ui/ or whm-plugin/ — it is a build artifact, not something to
# edit by hand.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PUBLISH_URL="${1:-https://storage.gosecureserver.in}"
PUBLISH_URL="${PUBLISH_URL%/}"
OUT_DIR="$REPO_ROOT/dist"
OUT_FILE="$OUT_DIR/install.sh"
mkdir -p "$OUT_DIR"
rm -f "$OUT_DIR/install-standalone.sh"

FILES=(
  VERSION
  bin/deploy.sh
  bin/guard
  bin/guard.php
  bin/self-update.sh
  etc/cron/skyserver-storage-guard
  etc/logrotate/skyserver-storage-guard
  etc/skyserver-storage-guard.conf.example
  lib/guard-lib.php
  plugin/api.live.php
  plugin/index.live.php
  plugin/liveapi.php
  plugin/notice.php
  plugin/skyserver_storage.conf
  plugin/skyserver_storage.png
  plugin/skyserver_storage.svg
  scripts/uninstall.sh
  ui/sky-ui.php
  whm-plugin/index.cgi
  whm-plugin/skyserver_storage_guard.appconfig
)

token_for() { echo "$1" | tr -c 'A-Za-z0-9' '_'; }

{
cat <<HEADER
#!/bin/bash
# SkyServer Storage Guard v$(cat "$REPO_ROOT/VERSION") — installer and updater.
# SKYSERVER-STORAGE-GUARD-INSTALLER
#
# Run as root on any WHM/cPanel server:
#
#   curl -sSL $PUBLISH_URL/install.sh | bash
#
# Self-contained: every file is inside this script, nothing is fetched.
# Running it again on a server that has it installed updates it in place —
# settings, scan reports and quarantined files are kept.
#
# Generated by scripts/build-installer.sh — edit the source and rebuild.
set -euo pipefail

INSTALL_DIR="/opt/skyserver-storage-guard"
PUBLISH_URL="$PUBLISH_URL"
HEADER
cat <<'HEADER'

log()  { echo "[storage-guard] $*"; }
die()  { echo "[storage-guard] ERROR: $*" >&2; exit 1; }

[ "$(id -u)" -eq 0 ]     || die "This installer must be run as root."
[ -d /usr/local/cpanel ] || die "cPanel/WHM installation not found at /usr/local/cpanel."
command -v base64 >/dev/null 2>&1 || die "base64 (coreutils) is required."
command -v php >/dev/null 2>&1 || [ -x /usr/local/cpanel/3rdparty/bin/php ] \
  || die "No PHP found — Storage Guard needs PHP (cPanel normally ships it)."

if [ -f "$INSTALL_DIR/VERSION" ]; then
  log "Updating from v$(cat "$INSTALL_DIR/VERSION") — settings and reports are kept."
else
  log "Installing into $INSTALL_DIR..."
fi
mkdir -p "$INSTALL_DIR"
HEADER

for f in "${FILES[@]}"; do
  token="$(token_for "$f")"
  echo
  echo "mkdir -p \"\$INSTALL_DIR/$(dirname "$f")\""
  echo "base64 -d > \"\$INSTALL_DIR/$f\" <<'FILE_${token}'"
  base64 "$REPO_ROOT/$f"
  echo "FILE_${token}"
done

cat <<'FOOTER'

chmod +x "$INSTALL_DIR"/bin/guard "$INSTALL_DIR"/bin/*.sh "$INSTALL_DIR"/scripts/*.sh
# Where WHM's "Check for Updates" looks for new releases.
echo "$PUBLISH_URL" > "$INSTALL_DIR/UPDATE_URL"

# Config, cron, logrotate and both panels live in deploy.sh, so the
# installer and the in-place updater stay in step.
"$INSTALL_DIR/bin/deploy.sh"

echo
log "Install complete. Next steps:"
log "  1) WHM → Plugins → SkyServer Storage Guard → Scan all accounts."
log "  2) Look through what it found. Nothing is sent to customers and nothing"
log "     is deleted until you choose to."
log "  3) Settings → set the From address and support contact, send a test email."
log "  4) The nightly scan then runs at 03:30. Automatic reminders and"
log "     suspension stay off until you switch them on."
FOOTER
} > "$OUT_FILE"

chmod +x "$OUT_FILE"
cp "$REPO_ROOT/VERSION" "$OUT_DIR/VERSION"
bash -n "$OUT_FILE"
echo "Built v$(cat "$REPO_ROOT/VERSION") for $PUBLISH_URL ($(du -h "$OUT_FILE" | cut -f1))"
echo "Upload both to the web root of $PUBLISH_URL:"
echo "  $OUT_FILE"
echo "  $OUT_DIR/VERSION"
echo "Then on a server:  curl -sSL $PUBLISH_URL/install.sh | bash"
