#!/bin/bash
# Bundles the whole module into one self-contained installer at
# dist/install-standalone.sh. Every runtime file is embedded as base64, so
# it needs no `git clone` and works even though this repo is private — host
# it anywhere and run it with `curl -sSL <url> | bash`.
#
# Re-run after changing anything under bin/, lib/, etc/, plugin/, ui/ or
# whm-plugin/ — it is a build artifact, not something to edit by hand.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT_DIR="$REPO_ROOT/dist"
OUT_FILE="$OUT_DIR/install-standalone.sh"
mkdir -p "$OUT_DIR"

FILES=(
  VERSION
  bin/deploy.sh
  bin/guard
  bin/guard.php
  bin/self-update.sh
  etc/cron/skyserver-storage-guard
  etc/logrotate/skyserver-storage-guard
  etc/skyserver-storage-guard.conf.example
  lib/guard-lib.php
  plugin/api.live.php
  plugin/index.live.php
  plugin/liveapi.php
  plugin/notice.php
  plugin/skyserver_storage.conf
  plugin/skyserver_storage.png
  plugin/skyserver_storage.svg
  scripts/uninstall.sh
  ui/sky-ui.php
  whm-plugin/index.cgi
  whm-plugin/skyserver_storage_guard.appconfig
)

token_for() { echo "$1" | tr -c 'A-Za-z0-9' '_'; }

{
cat <<'HEADER'
#!/bin/bash
# SkyServer Storage Guard — standalone installer (self-contained, no
# git/GitHub access required). Generated by scripts/build-installer.sh —
# edit the source files and rebuild instead of editing this.
#
# Run as root on the WHM/cPanel server:
#
#   curl -sSL https://<your-host>/storage-guard.sh | bash
set -euo pipefail

INSTALL_DIR="/opt/skyserver-storage-guard"

log()  { echo "[storage-guard] $*"; }
die()  { echo "[storage-guard] ERROR: $*" >&2; exit 1; }

[ "$(id -u)" -eq 0 ]     || die "This installer must be run as root."
[ -d /usr/local/cpanel ] || die "cPanel/WHM installation not found at /usr/local/cpanel."

log "Writing module files to $INSTALL_DIR..."
mkdir -p "$INSTALL_DIR"
HEADER

for f in "${FILES[@]}"; do
  token="$(token_for "$f")"
  echo
  echo "mkdir -p \"\$INSTALL_DIR/$(dirname "$f")\""
  echo "base64 -d > \"\$INSTALL_DIR/$f\" <<'FILE_${token}'"
  base64 "$REPO_ROOT/$f"
  echo "FILE_${token}"
done

cat <<'FOOTER'

chmod +x "$INSTALL_DIR"/bin/guard "$INSTALL_DIR"/bin/*.sh "$INSTALL_DIR"/scripts/*.sh

# Config, cron, logrotate and both panels live in deploy.sh, so the
# installer and the in-place updater stay in step.
"$INSTALL_DIR/bin/deploy.sh"

echo
log "Install complete. Next steps:"
log "  1) WHM → Plugins → SkyServer Storage Guard → Scan all accounts."
log "  2) Look through what it found. Nothing is sent to customers and nothing"
log "     is deleted until you choose to."
log "  3) Settings → set the From address and support contact, send a test email."
log "  4) The nightly scan then runs at 03:30. Automatic reminders and"
log "     suspension stay off until you switch them on."
FOOTER
} > "$OUT_FILE"

chmod +x "$OUT_FILE"
echo "Built: $OUT_FILE ($(wc -l < "$OUT_FILE") lines, $(du -h "$OUT_FILE" | cut -f1))"
